name: Build and deploy GH Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
